### ISSUE TITLE
[Suggestion] Add "category" in table

### ISSUE THREAD

**Issue by mount2010** [Person1873/FOSS_how_to_contribute#1]
Given that this project is to provide a list of FOSS projects to donate to, it should include categories (or headers) under which projects can be categorized. This would help people who are looking for a specific kind of project to donate to. For instance, "Desktop Environments", "Development Libraries", "OSes", "FOSS Foundations/Nonprofits", "Privacy", etc.

**Comment by Person1873** [comment]
Definitely a good idea, but I'd rather keep the scope small to start with (as it's already a pretty massive undertaking)
Once I've finished working on the next commit (getting a base list of projects) as well as getting project URL's and donation links I'll accept a PR adding this.

9 Apr 2024 6:07:38 pm mount2010 ***@***.***>:

**Comment by Person1873** [comment]
To reduce the workload i've had Chat-GPT generate the initial list including category, call this closed :)
